// Run with: node --test tests/frontend_unit.test.cjs
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const source=name=>fs.readFileSync(path.join(__dirname,'../backend/static',name),'utf8');
function element(){return {value:'',hidden:false,textContent:'',innerHTML:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},querySelector(){return element()},querySelectorAll(){return []}};}
function context(){const elements=new Map();const get=id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id)};const c={URL,URLSearchParams,Intl,Date,Math,Number,String,JSON,Promise,Map,Set,console,setTimeout,clearTimeout,matchMedia:()=>({matches:false,addEventListener(){}}),location:{origin:'http://test',href:'http://test/?day=2026-09-05',search:'?day=2026-09-05'},history:{replaceState(_,__,url){const u=String(url);c.location.href=u;c.location.search=u.includes('?')?u.slice(u.indexOf('?')):'';}},fetch:async()=>({ok:true,json:async()=>({timezone:'Asia/Shanghai'})}),document:{getElementById:get,querySelector:()=>element(),querySelectorAll:()=>[],addEventListener(){},createElement:element},addEventListener(){}};c.window=c;return {c:vm.createContext(c),get};}
test('date validation and navigation handle leap days without UTC date drift',async()=>{const {c}=context();vm.runInContext(source('ui.js'),c);await c.ActivityUI.ready;assert.equal(c.ActivityUI.validDay('2026-02-30'),false);assert.equal(c.ActivityUI.validDay('2024-02-29'),true);assert.equal(c.ActivityUI.shift('2024-03-01',-1),'2024-02-29');assert.equal(c.ActivityUI.initialDay(),'2026-09-05');assert.equal(c.ActivityUI.clock('2026-09-05T01:00:00Z'),'09:00');assert.equal(c.ActivityUI.duration(3599),'1h');});
test('day param is consumed once so refresh lands back on today',async()=>{const {c}=context();vm.runInContext(source('ui.js'),c);await c.ActivityUI.ready;assert.equal(c.ActivityUI.initialDay(),'2026-09-05');assert.equal(c.location.search,'');assert.equal(c.ActivityUI.initialDay(),c.ActivityUI.today());});
test('pie charts preserve category identities and reuse instances for data transitions',async()=>{const {c}=context();let created=0,options;const handlers={};c.echarts={init:el=>{created++;return {getDom:()=>el,setOption:value=>options=value,off:name=>delete handlers[name],on:(name,fn)=>handlers[name]=fn,resize(){}}}};vm.runInContext(source('ui.js'),c);let selected;c.ActivityUI.pie('pie',[{category:'学习',seconds:3600}],x=>selected=x);c.ActivityUI.pie('pie',[{category:'工作',seconds:1800}],x=>selected=x);assert.equal(created,1);assert.equal(options.series[0].data[0].name,'工作');handlers.click({name:'工作'});assert.equal(selected,'工作');assert.equal(options.animationDurationUpdate,450);});
test('history query preserves day, dimension and escaped device identifier',()=>{const {c}=context();const s=source('app.js');vm.runInContext('let selectedDay="2026-09-05";let selectedDevice="pc & lab";'+s.slice(s.indexOf('function withDay('),s.indexOf('function formatClock(')),c);assert.equal(c.withDevice('/api/v1/summary/today?dimension=purpose'),'/api/v1/summary/today?dimension=purpose&day=2026-09-05&device_id=pc+%26+lab');});
test('slower old report cannot overwrite a newly selected day',async()=>{const {c,get}=context();const pending=[];const renders=[];c.ActivityUI={setTimezone(){},json:url=>new Promise(resolve=>pending.push({url,resolve})),reflection(){},syncDay(){}};for(const fn of ['renderHeadline','renderStats','renderMainTimeline','renderDistribution','renderRankings','renderMemories','renderOfflineRecords'])c[fn]=fn==='renderHeadline'?report=>renders.push(report.date):()=>{};c.showToast=()=>{};vm.runInContext('let reportGeneration=0;let currentDay="2026-09-05";let lastReport=null;let purposeSummary=[];',c);const s=source('daily.js');vm.runInContext(s.slice(s.indexOf('async function loadReport()'),s.indexOf('document.querySelectorAll("[data-daily-dimension]")')),c);const first=c.loadReport();vm.runInContext('currentDay="2026-09-06";',c);const second=c.loadReport();pending[2].resolve({date:'2026-09-06',combined_segments:[]});pending[3].resolve({categories:[]});await second;pending[0].resolve({date:'2026-09-05',combined_segments:[]});pending[1].resolve({categories:[]});await first;assert.deepEqual(renders,['2026-09-06']);assert.match(get('pageState').textContent,/2026-09-06/);});
test('failed date load hides report content instead of relabeling stale data',async()=>{const {c,get}=context();c.ActivityUI={json:async()=>{throw Error('offline')}};c.showToast=()=>{};vm.runInContext('let reportGeneration=0;let currentDay="2026-09-05";',c);const s=source('daily.js');vm.runInContext(s.slice(s.indexOf('async function loadReport()'),s.indexOf('document.querySelectorAll("[data-daily-dimension]")')),c);await c.loadReport();assert.equal(get('offlineSection').hidden,true);assert.match(get('pageState').textContent,/加载失败/);assert.match(get('dailySummary').textContent,/暂不可用/);});
test('comparison tooltips use custom-series object data and exact duration',()=>{const {c,get}=context();const charts={};const day={day:'2026-09-05',category:{categories:[{category:'学习',seconds:3600}]},purpose:{categories:[{category:'学习',seconds:3600}]},timeline:{segments:[{start_time_local:'2026-09-05T09:00:00+08:00',end_time_local:'2026-09-05T10:00:00+08:00',category:'学习',purpose:'学习',behavior:'阅读',duration_seconds:3600}]}};get('compareDimension').value='category';c.ActivityUI={colors:{学习:'#82cedd'},escape:x=>x,duration:x=>`${x}s`,clock:x=>x.slice(11,16),today:()=> '2026-09-09',chart:(id,opt)=>{charts[id]=opt;return {off(){},on(){}}}};c.loaded=[day];const s=source('compare.js');vm.runInContext('const UI=ActivityUI;const dimension=document.getElementById("compareDimension");const seconds=(day,key)=>day.category.categories.find(x=>x.category===key)?.seconds||0;const go=()=>{};'+s.slice(s.indexOf('  function render()'),s.indexOf('  async function load()')),c);c.render();const opt=charts.compareLanes;const text=opt.tooltip.formatter({data:opt.series[0].data[0]});assert.match(text,/09:00—10:00/);assert.match(text,/3600s/);assert.equal(charts.compareBars.series[0].data[0],1);});
