plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ouyangru.activitytimeline'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ouyangru.activitytimeline'
        minSdk 29
        targetSdk 35
        versionCode 2
        versionName '0.2.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.work:work-runtime:2.11.2'
}
